
#------------------------
# DIYConfig配置文件
# 服务将返回一个需要解析文件map
# 其中的key是各自的相对所在的主配置目录的相对路径,但是包括相对路径
# 这样便于区分不同主目录下的配置文件
#-----------------------

#版本信息,禁止修改
#服务将校验值
version: 1.0
#配置文件读取规则
readRule:
    #激活的环境
    #这里起名很重要
    #如果preyTarget是FileFlag
    #只要根配置文件目录下所有带指定正则表达式所匹配的文件将被载入
    #如果preyTarget是DirFlag那么这里指定的就是目录名,此时不能使用正则表达式
    #如果只想读取根配置文件所有文件(包含以及排除规则依然有效)配置文件,那么这里设置为null
    #---------------------------
    #prey有一个具有特殊意义的值
    #  prey: null
    #当设置这个值时preyTarget是失效的,建议preyTarget也为null
    #---------------------------
    #生产环境建议设置为null,当此值为null他将读取指定配置所有主目录下配置文件。
    #这样的目录结构更专业而不需要奇怪的特殊文件命名,看着极其反感，尤其SpringBoot配置文件组织结构,看着老瓜疼.
    #推荐的文件组织形式是：
    #主配置config目录下有三个文件
    #分别 dev test prod
    #所有不同环境配置文件分别存放，如果上线后就把其他环境备份移动到其他地方，提取prod所有文件包括子目录到主目录。然后设置
    #prey为null接着设置preyTarget为null最完美
    #匹配模式.*dev.*
    prey: .*dev.*
    #狩猎类型 FileFlag DirFlag null
    #FileFlag 读取具正则表达式匹配的文件
    #DirFlag 读取名为prey指定的文件夹下的文件
    #null 读取根所有主配置目录下的所有文件(排除规则依然有效)
    preyTarget: FileFlag
    #读取文件后将剔除的标记.例如:如果将读取*dev.*匹配的配置文件.当读取完成,为文件做索引的时候,
    #将依照给出的字符串,还原真正的文件名.
    #如config-dev.yml被索引后将变成 config.yml.
    fileMapFlagKey:
       - -dev
       - -prod
       - -test
    #配置文件顶级目录,这里可配置多个配置文件主目录,默认是项目的根目录.如果默认使用项目根目录则使用[]标记.注意一定区分大小写.
    #自定义请填写绝对路径,也可以配置单独的文件,是文件还是目录可以自动判断.
    #非项目下的都是绝对路径
    #-----------------------
    #如果想配置的目录在项目目录下
    #例：
    # - classpath:your/config/dir/or/file
    #-----------------------
    #一般项目只配置一个主配置目录，如果有多个为了区分不同主目录的文件。所以文件映射的key
    #会加上主配目录的名称，但是主要开发环境下默认的目录回事classes目录,这里设置为
    #项目的config目录。
    configFilePath:
        - classpath:config
    #排除不读取的配置文件或者目录
    exclude:
        #需要排除的文件或者目录,文件和目录在操作系统级别已经不能重名了.这里设置的名称是文件还是目录都可以,
        #如果为 null代表不用统配,如果有值则是统配,这里的统配将作用为所有主配置文件下的所有子目录.
        regex:
            - application.*
            - META-INF #在开发环境下不读取此目录
            #- org 可以在此排除包目录(根据具体项目排除)
        #统配和特殊列出的文件的或者目录是同时生效的不会互斥
        #任意一个文件只要符合regex和specialFile中一个都会被排除
        #如果都没有可以设置为[]
        specialFile:
          #这里的路径是相对于主配置目录(外部的或者内部)的相对路径
          #例:
          # config 目录下有一个子目录名曰 redis 在redis中有个配置文件redis.yml
          # 在config目录下有个文件 redis.yml 文件如果要区分必须写成 redis/redis.yml
          # 注意是相对路径没有前面没有分隔符
          # 以此类推下去
          - classpath:DIYConfig.yml
